# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x61uth_service.proto\x12\x03rpc\"2\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"%\n\rLoginResponse\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t2?\n\x0b\x41uthService\x12\x30\n\x05Login\x12\x11.rpc.LoginRequest\x1a\x12.rpc.LoginResponse\"\x00\x42\x08Z\x06\x61pi/v1b\x06proto3')



_LOGINREQUEST = DESCRIPTOR.message_types_by_name['LoginRequest']
_LOGINRESPONSE = DESCRIPTOR.message_types_by_name['LoginResponse']
LoginRequest = _reflection.GeneratedProtocolMessageType('LoginRequest', (_message.Message,), {
  'DESCRIPTOR' : _LOGINREQUEST,
  '__module__' : 'auth_service_pb2'
  # @@protoc_insertion_point(class_scope:rpc.LoginRequest)
  })
_sym_db.RegisterMessage(LoginRequest)

LoginResponse = _reflection.GeneratedProtocolMessageType('LoginResponse', (_message.Message,), {
  'DESCRIPTOR' : _LOGINRESPONSE,
  '__module__' : 'auth_service_pb2'
  # @@protoc_insertion_point(class_scope:rpc.LoginResponse)
  })
_sym_db.RegisterMessage(LoginResponse)

_AUTHSERVICE = DESCRIPTOR.services_by_name['AuthService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\006api/v1'
  _LOGINREQUEST._serialized_start=27
  _LOGINREQUEST._serialized_end=77
  _LOGINRESPONSE._serialized_start=79
  _LOGINRESPONSE._serialized_end=116
  _AUTHSERVICE._serialized_start=118
  _AUTHSERVICE._serialized_end=181
# @@protoc_insertion_point(module_scope)
