# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: filter_message.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import memory_message_pb2 as memory__message__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x66ilter_message.proto\x12\x03rpc\x1a\x14memory_message.proto\"i\n\x06\x46ilter\x12\x15\n\rmax_price_usd\x18\x01 \x01(\x01\x12\x15\n\rmin_cpu_cores\x18\x02 \x01(\r\x12\x13\n\x0bmin_cpu_ghz\x18\x03 \x01(\x01\x12\x1c\n\x07min_ram\x18\x04 \x01(\x0b\x32\x0b.rpc.MemoryB\x08Z\x06\x61pi/v1b\x06proto3')



_FILTER = DESCRIPTOR.message_types_by_name['Filter']
Filter = _reflection.GeneratedProtocolMessageType('Filter', (_message.Message,), {
  'DESCRIPTOR' : _FILTER,
  '__module__' : 'filter_message_pb2'
  # @@protoc_insertion_point(class_scope:rpc.Filter)
  })
_sym_db.RegisterMessage(Filter)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\006api/v1'
  _FILTER._serialized_start=51
  _FILTER._serialized_end=156
# @@protoc_insertion_point(module_scope)
