# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: laptop_message.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import memory_message_pb2 as memory__message__pb2
import processor_message_pb2 as processor__message__pb2
import storage_message_pb2 as storage__message__pb2
import keyboard_message_pb2 as keyboard__message__pb2
import screen_message_pb2 as screen__message__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14laptop_message.proto\x12\x03rpc\x1a\x14memory_message.proto\x1a\x17processor_message.proto\x1a\x15storage_message.proto\x1a\x16keyboard_message.proto\x1a\x14screen_message.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe5\x02\n\x06Laptop\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05\x62rand\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x15\n\x03\x63pu\x18\x04 \x01(\x0b\x32\x08.rpc.CPU\x12\x18\n\x03ram\x18\x05 \x01(\x0b\x32\x0b.rpc.Memory\x12\x16\n\x04gpus\x18\x06 \x03(\x0b\x32\x08.rpc.GPU\x12\x1e\n\x08storages\x18\x07 \x03(\x0b\x32\x0c.rpc.Storage\x12\x1b\n\x06screen\x18\x08 \x01(\x0b\x32\x0b.rpc.Screen\x12\x1f\n\x08keyboard\x18\t \x01(\x0b\x32\r.rpc.Keyboard\x12\x13\n\tweight_kg\x18\n \x01(\x01H\x00\x12\x13\n\tweight_lb\x18\x0b \x01(\x01H\x00\x12\x11\n\tprice_usd\x18\x0c \x01(\x01\x12\x14\n\x0crelease_year\x18\r \x01(\r\x12.\n\nupdated_at\x18\x0e \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x08\n\x06weightB\x08Z\x06\x61pi/v1b\x06proto3')



_LAPTOP = DESCRIPTOR.message_types_by_name['Laptop']
Laptop = _reflection.GeneratedProtocolMessageType('Laptop', (_message.Message,), {
  'DESCRIPTOR' : _LAPTOP,
  '__module__' : 'laptop_message_pb2'
  # @@protoc_insertion_point(class_scope:rpc.Laptop)
  })
_sym_db.RegisterMessage(Laptop)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\006api/v1'
  _LAPTOP._serialized_start=179
  _LAPTOP._serialized_end=536
# @@protoc_insertion_point(module_scope)
